Traceback (most recent call last):
  File "C:\Users\richa\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\richa\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\richa\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\richa\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\richa\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\richa\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\richa\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\richa\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Kij = np.asarray([[0, -0.11], [-0.11, 0]])
mix.kij_cubic(Kij)

eos1 = vdweos(mix)
model1 = virialgamma(mix,actmodel='uniquac')
eos1?
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mException[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_10804\2527899150.py[0m in [0;36m<module>[1;34m[0m
[0;32m      3[0m [1;33m[0m[0m
[0;32m      4[0m [0meos1[0m [1;33m=[0m [0mvdweos[0m[1;33m([0m[0mmix[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 5[1;33m [0mmodel1[0m [1;33m=[0m [0mvirialgamma[0m[1;33m([0m[0mmix[0m[1;33m,[0m[0mactmodel[0m[1;33m=[0m[1;34m'uniquac'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      6[0m [0mget_ipython[0m[1;33m([0m[1;33m)[0m[1;33m.[0m[0mrun_line_magic[0m[1;33m([0m[1;34m'pinfo'[0m[1;33m,[0m [1;34m'eos1'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\phasepy\actmodels\virialgama.py[0m in [0;36m__init__[1;34m(self, mix, virialmodel, actmodel)[0m
[0;32m    142[0m                 [0mself[0m[1;33m.[0m[0mactm_temp[0m [1;33m=[0m [0mactm_temp[0m[1;33m.[0m[0m__get__[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    143[0m             [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 144[1;33m                 [1;32mraise[0m [0mException[0m[1;33m([0m[1;34m'UNIQUAC parameters needed'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    145[0m [1;33m[0m[0m
[0;32m    146[0m         [1;32melif[0m [0mactmodel[0m [1;33m==[0m [1;34m'rk'[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mException[0m: UNIQUAC parameters needed
Exception: UNIQUAC parameters needed

