Traceback (most recent call last):
  File "C:\Users\richa\AppData\Roaming\Python\Python311\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\anaconda3\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%matplotlib notebook
from ipywidgets import *
import numpy as np
import matplotlib.pyplot as plt

from phasepy import component, mixture, preos
Tc=647.13
Pc=220.55
Vc=58
w=0.344861
Tr=1
water = component(name='water', Tc=Tc, Pc=Pc, w=w)
eos=preos(water,'mhv_unifac')
R=8.314 
##create the plot
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
plt.yscale('log')
plt.xscale('log')
plt.ylabel('P (bar)')
plt.xlabel(r'$V$ $(cm^3/mol)$')

v=np.logspace(np.log10(eos.b[0]*1.1),np.log10(1000*eos.b[0]),201)
line, = ax.plot(v,eos(Tr*Tc,v),label=r'T_r=%3.2f'%Tr)
ax.plot(v,eos(Tc,v),'--k',label=r'T_r=1')
ax.plot([Vc],[Pc],marker='o',c='r',markersize=10)
plt.xlim(min(v),max(v))
plt.ylim(0.01*Pc,100*Pc)
plt.legend()


##update the plot
def update(Tr = 1):
    line.set_data(v,eos(Tr*Tc,v))
    line.set_label(r'$T_r=%3.2f$'%Tr)
    plt.xlim(min(v),max(v))
    plt.ylim(0.01*Pc,100*Pc)
    plt.legend()
    fig.canvas.draw_idle()

interact(update,Tr=(0,3.0,0.01));


------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 6[0m
[0;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m----> 6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mphasepy[39;00m [38;5;28;01mimport[39;00m component, mixture, preos
[0;32m      7[0m Tc[38;5;241m=[39m[38;5;241m647.13[39m
[0;32m      8[0m Pc[38;5;241m=[39m[38;5;241m220.55[39m

[1;31mModuleNotFoundError[0m: No module named 'phasepy'
ModuleNotFoundError: No module named 'phasepy'

